#!/usr/bin/env bash
#
# snapshot-bridge-contract.sh — Capture the go_backend exports that
# native/bridge/bridge.go depends on, with their current signatures.
#
# The bridge links go_backend by source (replace => ../../go_backend), so a
# changed signature breaks `go build` in native/bridge. This snapshot adds a
# second safety net: it makes signature changes (and behavioural-only renames)
# diffable across an upstream sync.
#
# Usage:
#   scripts/snapshot-bridge-contract.sh            # rewrite docs/bridge-contract.txt
#   scripts/snapshot-bridge-contract.sh --check    # diff against the committed snapshot
#
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

OUT="docs/bridge-contract.txt"
BRIDGE="native/bridge/bridge.go"
CHECK=false
[[ "${1:-}" == "--check" ]] && CHECK=true

gen() {
  local base
  base="$(git rev-parse --short vendor/spotiflac-base 2>/dev/null || echo '?')"
  echo "# Bridge contract surface — go_backend exports called by native/bridge/bridge.go"
  echo "# Baseline: vendor/spotiflac-base ($base). Regenerate + diff after each sync."
  echo "# Generated by: scripts/snapshot-bridge-contract.sh"
  echo "# If any signature here changes upstream, native/bridge must be updated."
  echo ""
  grep -oE "gobackend\.[A-Za-z0-9_]+" "$BRIDGE" | sed 's/gobackend\.//' | sort -u | while read -r s; do
    grep -rhE "^func $s\(" go_backend/*.go 2>/dev/null | grep -v _test.go | head -1
  done
}

if [[ "$CHECK" == true ]]; then
  if diff -u "$OUT" <(gen) ; then
    echo "✓ Bridge contract unchanged vs committed snapshot."
  else
    echo
    echo "!! Contract drift detected. Update native/bridge/bridge.go +"
    echo "   lib/services/backend_bridge.dart to match, then re-run without --check."
    exit 1
  fi
else
  gen > "$OUT"
  echo "Wrote $OUT"
fi
